version: '3.7'

volumes:
  postgres_data:
  static:
  media:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.example
  web:
    image: okodit/foodgram
    restart: always
    command: gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - .env.example
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
  nginx:
    image: nginx:1.19.6
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/

    ports:
      - '80:80'
    depends_on:
      - web

  volumes:
    postgres_data:
    static_value:
    media_value:
