version: '3.7'

volumes:
  postgres_data:
  static:
  media:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.example
  web:
    image: okodit/foodgram
    restart: always
    depends_on:
      - db
    env_file:
      - .env.example
    volumes:
      - ./static:/code/static/
      - ./media:/code/media/
  nginx:
    image: nginx:1.19.6
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/code/static/
      - ./media:/code/media/

    ports:
      - '80:80'
    depends_on:
      - web